<!doctype html>
<html data-page="home" lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <title>Potrivit - Privacy Policy</title>
        <?php if (strlen(Config::get()->googleAnalytics())):?><script async src="https://www.googletagmanager.com/gtag/js?id=<?=Config::get()->googleAnalytics()?>"></script><?php endif;?>
        
        <script>
            ((path, host) => {
                do {
                    if ('potrivit.gitlab.io' === host) {
                        window.location.href = `https://<?=Config::get()->domainLive()?>/${path.replace(/(?:^\/potrivit\/|\bindex.html$)/ig,'')}`;
                        break;
                    } else {
                        if ('www.<?=Config::get()->domainLive()?>' === host || path.match(/\/index.html$/ig)) {
                            window.location.href = `https://<?=Config::get()->domainLive()?>${path.replace(/\bindex.html$/ig,'')}`;
                            break;
                        }
                    }
                } while(false);
            })(window.location.pathname, window.location.hostname);
            <?php if (strlen(Config::get()->googleAnalytics())):?>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', '<?=Config::get()->googleAnalytics()?>');<?php endif;?>
        </script>
        <script defer src="../<?=Render_Listing::FOLDER_MAIN?>/js/main.js"></script>
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="../<?=Render_Listing::FOLDER_MAIN?>/css/main.css"/>
        <link rel="dns-prefetch" href="//ps.w.org"/>
        <link rel="manifest" id="pwa_manifest"/>
        <link rel="canonical" href="https://<?=Config::get()->domainLive()?>/privacy-policy/"/>
        <link rel="shortcut icon" type="image/ico" href="../favicon.ico"/>
        <link rel="apple-touch-icon" href="../<?=Render_Listing::FOLDER_MAIN?>/img/512.png"/>
        <link rel="license" href="<?=Config::get()->licenseUri()?>"/>
        
        <meta name="generator" content="<?=Config::get()->siteName();?> SSG v.<?=Config::get()->version()?> | markjivko.com"/>
        <meta name="author" content="markjivko.com"/>
        <meta name="referrer" content="origin"/>
        <meta name="referrer" content="origin-when-crossorigin"/>
        <meta name="referrer" content="origin-when-cross-origin"/>
        <meta name="description" content="Privacy Policy for <?=Config::get()->domainLive();?>"/>
        <meta name="theme-color" content="#13d213"/>
        <meta name="msapplication-TileColor" content="#13d213"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta property="og:title" content="Potrivit - Privacy Policy"/>
        <meta property="og:url" content="https://<?=Config::get()->domainLive()?>/"/>
        <meta property="og:site_name" content="<?=Config::get()->siteName();?>"/>
        <meta property="og:description" content="Privacy Policy for <?=Config::get()->domainLive();?>"/>
        <meta property="og:type" content="website"/>
        <meta property="og:image" content="https://<?=Config::get()->domainLive()?>/<?=Render_Listing::FOLDER_MAIN?>/img/512.png"/>
    </head>
    <body>
        <header>
            <div class="container">
                <div class="col part-top">
                    <a class="icon" href="https://<?= Config::get()->domainLive()?>/">Potrivit</a>
                </div>
                <div class="col part-cta">
                    <h1>Privacy Policy</h1>
                    <h2>tl;dr: No cookies, no tracking, just <b>Google Analytic</b>s</h2>
                </div>
            </div>
            <div data-role="delim">
                <svg width="1440" fill="#ffffff" height="0" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1440 150"><path d="M 0 26.1978 C 275.76 83.8152 430.707 65.0509 716.279 25.6386 C 930.422 -3.86123 1210.32 -3.98357 1439 9.18045 C 2072.34 45.9691 2201.93 62.4429 2560 26.198 V 172.199 L 0 172.199 V 26.1978 Z"></path></svg>
            </div>
        </header>
        <main>
            <div class="container">
                <h3>PRIVACY POLICY</h3>
                <p>This Privacy Policy describes how your personal information is collected, used, and shared when you visit <a href="https://<?=Config::get()->domainLive()?>">https://<?=Config::get()->domainLive()?></a> (the "Site").</p>

                <h3>PERSONAL INFORMATION WE COLLECT</h3>
                <p>When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically-collected information as "Device Information."</p>
                <p>We collect Device Information using the following technologies: <ul>
                    <li>"Log files" track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.</li>
                    <li>"Web beacons," "tags," and "pixels" are electronic files used to record information about how you browse the Site.</li>
                </ul></p>
                <p>We do not use any cookies and all pages are static. We do not track your searches on the Site.</p>
                <p>When we talk about "Personal Information" in this Privacy Policy, we are talking both about Device Information and Order Information.</p>

                <h3>HOW DO WE USE YOUR PERSONAL INFORMATION?</h3>
                <p>We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site (for example, by generating analytics about how our customers browse and interact with the Site, and to assess the success of our marketing and advertising campaigns).</p>
                <p>The only service used to track your visit on the Site is <b>Google Analytics</b>.</p>

                <h3>SHARING YOUR PERSONAL INFORMATION</h3>
                <p>We use <b>Google Analytics</b> to help us understand how our customers use the Site -- you can read more about how Google uses your Personal Information here: <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noreferrer nofollow">https://www.google.com/intl/en/policies/privacy/</a>. You can also opt-out of <b>Google Analytics</b> here: <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noreferrer nofollow">https://tools.google.com/dlpage/gaoptout</a>.</p>
                <p>Finally, we may also share your Personal Information to comply with applicable laws and regulations, to respond to a subpoena, search warrant or other lawful request for information we receive, or to otherwise protect our rights.</p>
                <p>We do not use targeted advertising.</p>

                <h3>DO NOT TRACK</h3>
                <p>Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.</p>

                <h3>YOUR RIGHTS</h3>
                <p>If you are a European resident, you have the right to access personal information we hold about you and to ask that your personal information be corrected, updated, or deleted, however we never collect any personal information.</p>

                <h3>CHANGES</h3>
                <p>We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.</p>

                <h3>CONTACT US</h3>
                <p>For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us on <a rel="noreferrer noindex" target="_blank" href="https://discord.com/invite/Q6CrN6Vk7N">Discord</a>.</p>
            </div>
            <div data-role="delim">
                <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="0" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M0 100 C40 0 60 0 100 100 Z"></path></svg>
            </div>
        </main>
        <footer>
            <div class="container">
                &copy; <?=date('Y')?>
                <a target="_blank" rel="noreferrer nofollow" href="https://translate.google.com/?sl=ro&amp;text=potrivit">potrivit</a>
                by <a target="_blank" rel="noreferrer nofollow author" href="https://markjivko.com">Mark Jivko</a> <a href="/privacy-policy/">Privacy Policy</a>
            </div>
        </footer>
    </body>
</html>
